name: terraform

on:
  push:
    branches:
    - main
  pull_request:
    branches: [ main ]
  #To trigger manual
  workflow_dispatch: 

jobs:
  terraform:
    #runs-on: [self-hosted, x64, linux, research]
    runs-on: ubuntu-latest
    container:
      image: hashicorp/terraform
    #  image: .github/workflows/Dockerfile
    env:
      GITHUB_TOKEN: ${{ secrets.SYNERGY_DEVOPS_ACCESS_GITHUB_TOKEN }}

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v2.4.0

    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      run: terraform init

    # Checks that all Terraform configuration files adhere to a canonical format
    #- name: Terraform Format
    #  run: terraform fmt -check

    # Generates an execution plan for Terraform
    - name: Terraform Plan
      run: terraform plan
